name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: PrimerParcial-Electiva2/PrimerParcial-Electiva2
        run: npm install

      - name: Build application (opcional)
        working-directory: PrimerParcial-Electiva2/PrimerParcial-Electiva2
        run: npm run build # Si es necesario

      - name: Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        working-directory: PrimerParcial-Electiva2/PrimerParcial-Electiva2
        run: npx surge ./build manudls-pl.surge.sh --token $SURGE_TOKEN
