name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: configura nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Surge
        run: npm install --global surge

      - name: Build and Deploy
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_API_KEY }}
        run: |
          surge --project ./ --domain Orbea.surge.sh
